collection-acropolis.yaml, collection-blueprint.yaml, collection-citadel.yaml, collection-dome.yaml, gazebo10.yaml, gazebo11.yaml, gazebo7.yaml, gazebo8.yaml, gazebo9.yaml, ign-gazebo1.yaml, ign-gazebo2.yaml, ign-gazebo3.yaml, ign-gazebo4.yaml, ign-launch0.yaml, ign-launch1.yaml, ign-launch2.yaml, ign-launch3.yaml, ign-physics1.yaml, ign-physics2.yaml, ign-physics3.yaml, ign-sensors1.yaml, ign-sensors2.yaml, ign-sensors3.yaml, ign-sensors4.yaml, sdformat9.yaml
Signed-off-by: Louise Poubel <louise@openrobotics.org>
=> GitHub for SDFormat

gazebo10.yaml, gazebo11.yaml, gazebo7.yaml, gazebo8.yaml, gazebo9.yaml
This fixes https://github.com/osrf/gazebo/issues/2771
=> Fix broken links in gazebo*.yaml files

ign-cmake3.yaml, ign-common4.yaml, ign-math7.yaml, ign-plugin2.yaml
Prep for changing default branches.
Builds on top of #9 
The branches have already been created upstream.
=> master -> main

collection-edifice.yaml
Until we need to bump any libraries, Edifice is exactly the same as Dome.
=> Add Edifice collection

collection-edifice.yaml, ign-gazebo5.yaml, ign-gui5.yaml, ign-launch4.yaml, ign-sensors5.yaml
Part of https://github.com/ignition-tooling/release-tools/issues/331
=> Bump in edifice: ign-rendering to 5

sdformat11.yaml
I forgot to add sdformat11 in #12.
This is needed to run the script from https://github.com/ignition-tooling/release-tools/pull/333 to address https://github.com/ignition-tooling/release-tools/issues/360
=> Add sdformat11

collection-edifice.yaml, ign-fuel-tools6.yaml, ign-gazebo5.yaml, ign-gui5.yaml, ign-launch4.yaml, ign-sensors5.yaml, ign-transport10.yaml
Addressing https://github.com/ignition-tooling/release-tools/issues/362
=> Bump in edifice: ign-msgs7, ign-transport10, ign-fuel-tools6

collection-edifice.yaml, ign-gazebo5.yaml, ign-launch4.yaml, ign-physics4.yaml, ign-sensors5.yaml
Addresses https://github.com/ignition-tooling/release-tools/issues/360
=> Bump in edifice: sdformat11 and ign-physics4

ign-common4.yaml
Part of [ign-common #161](https://github.com/ignitionrobotics/ign-common/issues/161)
=> Add ign-utils1 dependency for ign-common4

collection-edifice.yaml, ign-fuel-tools6.yaml, ign-gazebo5.yaml, ign-gui5.yaml, ign-launch4.yaml, ign-physics4.yaml, ign-rendering5.yaml, ign-sensors5.yaml
Signed-off-by: Michael Carroll <michael@openrobotics.org>
=> Bump in edifice: ign-common4

ign-transport10.yaml
Needed by https://github.com/ignitionrobotics/ign-transport/pull/216
=> ign-transport10.yaml: add ign-utils

collection-edifice.yaml, ign-common4.yaml, ign-fuel-tools6.yaml, ign-gazebo5.yaml, ign-gui5.yaml, ign-launch4.yaml, ign-msgs7.yaml, ign-physics4.yaml, ign-rendering5.yaml, ign-sensors5.yaml, ign-transport10.yaml, ign-utils1.yaml, sdformat11.yaml
To be merged after all branches have been created.
They're being created as we make stable releases.
https://github.com/ignition-tooling/release-tools/issues/421
=> Use stable branches for Edifice

ign-common5.yaml, ign-fuel-tools7.yaml, ign-gazebo6.yaml, ign-gui6.yaml, ign-launch5.yaml, ign-msgs8.yaml, ign-physics5.yaml, ign-rendering6.yaml, ign-sensors3.yaml, ign-sensors4.yaml, ign-sensors5.yaml, ign-sensors6.yaml, ign-transport11.yaml, ign-utils2.yaml, sdformat12.yaml
Similar to https://github.com/ignition-tooling/gazebodistro/pull/12/
https://github.com/ignition-tooling/release-tools/issues/421
=> Add files for new major versions (post Edifice)

ign-physics5.yaml
=> Bumps in fortress : ign-physics5

ign-transport11.yaml
=> Bumps in fortress : ign-transport11

ign-sensors6.yaml
=> Bumps in fortress : ign-sensors6

ign-gui6.yaml
=> Bumps in fortress : ign-gui6

ign-fuel-tools7.yaml
=> Bumps in fortress : ign-fuel-tools7

ign-launch5.yaml
=> Bumps in fortress : ign-launch5

ign-gazebo6.yaml
=> Bumps in fortress : ign-gazebo6

collection-fortress.yaml
=> Bumps in fortress : ign-fortress

collection-fortress.yaml, ign-fuel-tools7.yaml, ign-gazebo6.yaml, ign-gui6.yaml, ign-launch5.yaml, ign-msgs8.yaml, ign-physics5.yaml, ign-rendering6.yaml, ign-sensors6.yaml, ign-transport11.yaml, sdformat12.yaml
To be merged after all stable branches are created.
ignition-tooling/release-tools#459
=> Use stable branches for Fortress

collection-garden.yaml
Part of https://github.com/ignition-tooling/release-tools/issues/527
Until we bump dependencies, Garden is the same as Fortress
=> Add Garden collection

ign-gui7.yaml
=> Bumps in garden : ign-gui7

ign-sensors7.yaml
=> Bumps in garden : ign-sensors7

ign-launch6.yaml
=> Bumps in garden : ign-launch6

collection-garden.yaml
=> Bumps in garden : ign-garden

ign-transport12.yaml
=> Bumps in garden : ci_matching_branch/bump_garden_ign-transport12

ign-fuel-tools8.yaml
=> Bumps in garden : ci_matching_branch/bump_garden_ign-fuel-tools8

ign-sensors7.yaml
=> Bumps in garden : ci_matching_branch/bump_garden_ign-sensors7

ign-gui7.yaml
=> Bumps in garden : ci_matching_branch/bump_garden_ign-gui7

ign-gazebo7.yaml
=> Bumps in garden : ci_matching_branch/bump_garden_ign-gazebo7

ign-launch6.yaml
=> Bumps in garden : ci_matching_branch/bump_garden_ign-launch6

collection-garden.yaml
=> Bumps in garden : ci_matching_branch/bump_garden_ign-garden

ign-math4.yaml
This should help fix [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign_math-ign-4-win&build=1)](https://build.osrfoundation.org/job/ign_math-ign-4-win/1/) https://build.osrfoundation.org/job/ign_math-ign-4-win/1/
=> ign-math4: add yaml file

ign-common5.yaml
=> Bumps in garden: ign-common5 use ign-math7

sdformat13.yaml
=> Bumps in garden: sdformat13 use ign-math7

ign-msgs9.yaml
=> Bumps in garden: ign-msgs9 use ign-math7

ign-transport12.yaml
=> Bumps in garden: ign-transport12 use ign-math7

ign-rendering7.yaml
=> Bumps in garden: ign-rendering7 use ign-math7 and ign-common5

ign-fuel-tools8.yaml
=> Bumps in garden: ign-fuel-tools8 use common5, math7

ign-gui7.yaml
=> Bumps in garden : ign-gui7 depend on ign-math7 and ign-common5

ign-physics6.yaml
=> Bumps in garden: ign-physics6 use ign-math7, ign-common5 and sdformat13

ign-sensors7.yaml
=> Bumps in garden: ign-sensors7 use ign-math7, ign-common5 and sdformat13 

ign-gazebo7.yaml
=> Bumps in garden: ign-gazebo7 use ign-math7, ign-common5, sdformat13 and ign-physics6

ign-launch6.yaml
=> Bumps in garden: ign-launch6 depend on ign-common5, ign-math7, ign-physcs6, sdf13

collection-garden.yaml
=> Bumps in garden: ign-math7, ign-common5, ign-physics6, sdf13

ign-utils2.yaml
=> Bumps in garden : ign-utils2

sdformat13.yaml
=> Bumps in garden : sdformat13

ign-transport12.yaml
=> Bumps in garden : ign-transport12

ign-common5.yaml
=> Bumps in garden : ign-common5

ign-rendering7.yaml
=> Bumps in garden : ign-rendering7

ign-math7.yaml
=> Bumps in garden : ign-math7

ign-gazebo7.yaml
=> Bumps in garden : ign-plugin2, ign-utils2

ign-msgs9.yaml
=> Bumps in garden : ign-msgs9

ign-fuel-tools8.yaml
=> Bumps in garden : ign-fuel-tools8

ign-physics6.yaml
=> Bumps in garden : ign-physics6

ign-rendering7.yaml
=> Bumps in garden: ign-rendering7

ign-physics6.yaml
=> Bumps in garden: ign-physics6

ign-gazebo7.yaml
=> Bumps in garden : ign-gazebo7

ign-msgs1.yaml
Needed by gazebosim/gz-msgs#276
=> ign-msgs1.yaml: new file

collection-garden.yaml, gz-cmake4.yaml, ign-common5.yaml, ign-fuel-tools8.yaml, ign-gazebo7.yaml, ign-gui7.yaml, ign-launch6.yaml, ign-math7.yaml, ign-msgs9.yaml, ign-physics6.yaml, ign-plugin2.yaml, ign-rendering7.yaml, ign-sensors7.yaml, ign-tools2.yaml, ign-transport12.yaml, ign-utils2.yaml, sdformat13.yaml
* Part of https://github.com/gazebo-tooling/release-tools/issues/578
=> Add gz-cmake4, update cmake3

collection-garden.yaml, gz-tools3.yaml, ign-fuel-tools8.yaml, ign-gazebo7.yaml, ign-gui7.yaml, ign-launch6.yaml, ign-sensors7.yaml, ign-transport12.yaml, sdformat13.yaml
* Part of https://github.com/gazebo-tooling/release-tools/issues/578
=> Add gz-tools3, update tools2

collection-garden.yaml, gz-launch6.yaml, gz-sim8.yaml
* Follow up to https://github.com/gazebo-tooling/gazebodistro/pull/119
* Part of https://github.com/gazebo-tooling/release-tools/issues/578
=> Add gz-sim8, update gz-sim7

gz-sensors8.yaml
Signed-off-by: Ian Chen <ichen@osrfoundation.org>
https://github.com/gazebo-tooling/release-tools/issues/853
=> Bump sensors8 to depend on rendering8

collection-harmonic.yaml
Part of https://github.com/gazebo-tooling/release-tools/issues/856
=> Add Harmonic Collection

collection-harmonic.yaml
We'll use `msgs10` and `transport13` for Harmonic.
=> Bump Harmonic deps

collection-harmonic.yaml, gz-gui8.yaml, gz-launch7.yaml, gz-sensors8.yaml, gz-sim8.yaml
Update to use:
* msgs10: main branch
* transport13: main branch
* fuel-tools9: main branch
Part of https://github.com/gazebo-tooling/release-tools/issues/878
=> Update Harmonic deps

gz-sensors8.yaml
=> Bumps in harmonic : ci_matching_branch/bump_harmonic_gz-sensors8

gz-physics7.yaml
=> Bumps in harmonic : ci_matching_branch/bump_harmonic_gz-physics7

gz-sim8.yaml
=> Bumps in harmonic : ci_matching_branch/bump_harmonic_gz-sim8

gz-launch7.yaml
=> Bumps in harmonic : ci_matching_branch/bump_harmonic_gz-launch7

collection-harmonic.yaml
=> Bumps in harmonic : ci_matching_branch/bump_harmonic_gz-harmonic

gz-math8.yaml
=> Bumps in ionic : ci_matching_branch/bump_ionic_gz-math8

gz-plugin3.yaml
=> Bumps in ionic : ci_matching_branch/bump_ionic_gz-plugin3

gz-common6.yaml
=> Bumps in ionic : ci_matching_branch/bump_ionic_gz-common6

gz-msgs11.yaml
=> Bumps in ionic : ci_matching_branch/bump_ionic_gz-msgs11

gz-rendering9.yaml
See gazebo-tooling/release-tools#1027
=> Bumps in ionic : ci_matching_branch/bump_ionic_gz-rendering9

sdformat15.yaml
=> Bumps in ionic : ci_matching_branch/bump_ionic_sdformat15

gz-transport14.yaml
=> Bumps in ionic : ci_matching_branch/bump_ionic_gz-transport14

gz-gui9.yaml
=> Bumps in ionic : ci_matching_branch/bump_ionic_gz-gui9

gz-sensors9.yaml
=> Bumps in ionic : ci_matching_branch/bump_ionic_gz-sensors9

gz-physics8.yaml
=> Bumps in ionic : ci_matching_branch/bump_ionic_gz-physics8

gz-sim9.yaml
=> Bumps in ionic : ci_matching_branch/bump_ionic_gz-sim9

gz-launch8.yaml
=> Bumps in ionic : ci_matching_branch/bump_ionic_gz-launch8

collection-ionic.yaml, gz-fuel-tools10.yaml, gz-gui9.yaml, gz-launch8.yaml, gz-msgs11.yaml, gz-physics8.yaml, gz-rendering9.yaml, gz-sensors9.yaml, gz-sim9.yaml, gz-transport14.yaml, sdformat15.yaml
=> Bumps in ionic : ci_matching_branch/bump_ionic_gz-ionic

collection-ionic.yaml, gz-cmake4.yaml, gz-common6.yaml, gz-fuel-tools10.yaml, gz-gui9.yaml, gz-launch8.yaml, gz-math8.yaml, gz-msgs11.yaml, gz-physics8.yaml, gz-plugin3.yaml, gz-rendering9.yaml, gz-sensors9.yaml, gz-sim9.yaml, gz-transport14.yaml, gz-utils3.yaml, sdformat15.yaml
=> Use stable branch for gz-cmake4

collection-ionic.yaml, gz-common6.yaml, gz-fuel-tools10.yaml, gz-gui9.yaml, gz-launch8.yaml, gz-math8.yaml, gz-msgs11.yaml, gz-physics8.yaml, gz-plugin3.yaml, gz-rendering9.yaml, gz-sensors9.yaml, gz-sim9.yaml, gz-transport14.yaml, gz-utils3.yaml, sdformat15.yaml
=> Use stable branch for gz-utils3

collection-ionic.yaml, gz-common6.yaml, gz-fuel-tools10.yaml, gz-gui9.yaml, gz-launch8.yaml, gz-math8.yaml, gz-msgs11.yaml, gz-physics8.yaml, gz-rendering9.yaml, gz-sensors9.yaml, gz-sim9.yaml, gz-transport14.yaml, sdformat15.yaml
=> Ionic: use stable branch for gz-math8

collection-ionic.yaml, gz-gui9.yaml, gz-launch8.yaml, gz-rendering9.yaml, gz-sensors9.yaml, gz-sim9.yaml
=> Ionic: use stable branch for gz-rendering9

collection-ionic.yaml, gz-gui9.yaml, gz-launch8.yaml, gz-sim9.yaml
=> Use stable branch for gz-gui9

collection-ionic.yaml, gz-launch8.yaml, gz-sensors9.yaml, gz-sim9.yaml
=> Ionic: use stable branch for gz-sensors9

collection-ionic.yaml, gz-launch8.yaml, gz-physics8.yaml, gz-sensors9.yaml, gz-sim9.yaml, sdformat15.yaml
=> Ionic: use stable branch for sdformat15

collection-ionic.yaml, gz-fuel-tools10.yaml, gz-launch8.yaml, gz-sim9.yaml
=> Use stable branch for gz-fuel-tools10

collection-ionic.yaml, gz-common6.yaml, gz-fuel-tools10.yaml, gz-gui9.yaml, gz-launch8.yaml, gz-msgs11.yaml, gz-sensors9.yaml, gz-sim9.yaml, gz-transport14.yaml
=> Ionic: Use stable branch for gz-msgs11

collection-ionic.yaml, gz-gui9.yaml, gz-launch8.yaml, gz-physics8.yaml, gz-plugin3.yaml, gz-rendering9.yaml, gz-sensors9.yaml, gz-sim9.yaml
=> Use stable branch for gz-plugin3

gz-cmake5.yaml, gz-common7.yaml, gz-fuel-tools11.yaml, gz-gui10.yaml, gz-launch9.yaml, gz-math9.yaml, gz-msgs12.yaml, gz-physics9.yaml, gz-plugin4.yaml, gz-rendering10.yaml, gz-sensors10.yaml, gz-sim10.yaml, gz-transport15.yaml, gz-utils4.yaml, sdformat16.yaml
https://github.com/gazebo-tooling/release-tools/issues/1092
Each yaml file is a copy of the previous version except the library's own branch is changed to `main`
=> Add files for versions post-Ionic

collection-jetty.yaml
https://github.com/gazebo-tooling/release-tools/issues/1186
No version bumps yet so this is just a copy of ionic collection
=> Add jetty collection

gz-sim10.yaml
See https://github.com/gazebo-tooling/release-tools/issues/1235
=> Bumps in jetty : ci_matching_branch/bump_jetty_gz-sim10

gz-launch9.yaml
See https://github.com/gazebo-tooling/release-tools/issues/1235
=> Bumps in jetty : ci_matching_branch/bump_jetty_gz-launch9

collection-jetty.yaml
See https://github.com/gazebo-tooling/release-tools/issues/1235
=> Bumps in jetty: use gz-gui10, gz-sim10, gz-launch9

collection-jetty.yaml, gz-fuel-tools11.yaml, gz-gui10.yaml, gz-launch9.yaml, gz-msgs12.yaml, gz-sensors10.yaml, gz-sim10.yaml, gz-transport15.yaml
Part of https://github.com/gazebosim/gz-jetty/issues/25
=> Use stable branch for gz-msgs12
