gazebo-tooling/gazebodistro

collection-dome.yaml
ign-gazebo4.yaml
ign-gui4.yaml
ign-launch3.yaml
ign-physics3.yaml
ign-sensors4.yaml
ign-transport9.yaml
sdformat10.yaml

We need to create the branches first. Not sure if we want prereleases too.

Use msgs6/fuel-tools5/physics3/gazebo4/sdf10 in ignition-dome

---

ign-sensors4.yaml

Fixes CI for https://github.com/ignitionrobotics/ign-sensors/pull/31
Current SDFormat `master` is version 11.

sensors4 use sdf10

---

collection-dome.yaml
ign-fuel-tools5.yaml
ign-gazebo4.yaml
ign-gui4.yaml
ign-launch3.yaml
ign-msgs6.yaml
ign-physics3.yaml
ign-rendering4.yaml
ign-sensors4.yaml
ign-transport9.yaml

Update Dome branches

---

ign-fuel-tools6.yaml
ign-gazebo5.yaml
ign-gui5.yaml
ign-launch4.yaml
ign-msgs7.yaml
ign-physics4.yaml
ign-rendering5.yaml
ign-sensors5.yaml
ign-transport10.yaml

Each new major version is a copy of the version before it, the only difference being that the library's own branch is `main`.
None of the dependency relationships have changed since Dome. So, for example, `ign-gazebo5`'s dependencies are exactly the same as `ign-gazebo4`'s.

Add files for new major versions

---

ign-gazebo5.yaml
sdformat11.yaml

Also updated sdf11 to be in alphabetical order, this makes it easier to compare different yaml files.
Part of https://github.com/ignitionrobotics/ign-gazebo/issues/568

ign-gazebo5: depend on ign-utils1

---

ign-launch4.yaml
ign-physics4.yaml
ign-sensors5.yaml

Follow-up to #23, need to add `ign-utils` to dependents of `libsdformat11`.

Add ign-utils to libsdformat11 dependents

---

ign-gui5.yaml

This is required since ign-transport10 uses ign-utils as of https://github.com/ignitionrobotics/ign-transport/pull/216

ign-gui5.yaml: add ign-utils

---

ign-transport4.yaml

This version of ign-transport is used by gazebo9 and is still supported.

ign-transport4.yaml: new file

---

ign-rendering5.yaml

Needed by https://github.com/ignitionrobotics/ign-rendering/pull/264

rendering5 depend on utils1

---

collection-fortress.yaml

The fortress collection starts as an exact copy of Edifice. As we bump versions this file will have some `main` branches.
https://github.com/ignition-tooling/release-tools/issues/421

Add Fortress collection

---

ign-fuel-tools1.yaml

needed for https://github.com/ignition-tooling/release-tools/pull/430
the `ign-common1_colcon` branch is out of date; it's changes are already on `ign-common1`, so I updated the `gazebo9` file as well

ign-fuel-tools1.yaml: added to support colcon CI

---

ign-plugin2.yaml

Needed by https://github.com/osrf/homebrew-simulation/pull/1540

ign-plugin2.yaml: add ign-utils1

---

ign-gazebo7.yaml

Bumps in garden : ign-gazebo7

---

ign-math7.yaml

In support of multiple enhancements in `ign-math7`, namely:
* https://github.com/ignitionrobotics/ign-math/pull/299 for `ImplPtr`
* https://github.com/ignitionrobotics/ign-math/pull/283 for `NeverDestroyed`
Signed-off-by: Michael Carroll <michael@openrobotics.org>

Make `ign-math7` depend on `ign-utils`

---

ign-math7.yaml
ign-msgs9.yaml

* Follow up to #64 
* Alphabetize
* Add transient dependency to `ign-msgs9`, see broken build: https://build.osrfoundation.org/job/ign_msgs-pr-win/55/console

ign-math7 and ign-msgs9 depend on ign-utils

---

ign-plugin2.yaml

Bumps in garden : ign-plugin2

---

ign-msgs9.yaml
ign-transport12.yaml

Left-over from the transition when we had both `cmake2` and `cmake3`

Remove left-over ign-cmake2 for Garden

---

ign-tools2.yaml

* Goes with https://github.com/gazebosim/gz-tools/pull/96
Test Windows CI: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign_tools-pr-win&build=103)](https://build.osrfoundation.org/job/ign_tools-pr-win/103/)

gz-tools2 depend on gz-cmake3

---

ign-cmake4.yaml
ign-tools3.yaml

A bit of a race condition between 
* #115 
* #116 
And 
* #117 
We don't need symlinks after Garden, Gazebo-H+ are `gz`-native!

Remove ign- symlinks for post-Garden versions

---

collection-garden.yaml
gz-common5.yaml
gz-common6.yaml
gz-fuel-tools9.yaml
gz-gui8.yaml
gz-launch6.yaml
gz-launch7.yaml
gz-math7.yaml
gz-math8.yaml
gz-msgs10.yaml
gz-physics6.yaml
gz-physics7.yaml
gz-plugin2.yaml
gz-plugin3.yaml
gz-rendering7.yaml
gz-rendering8.yaml
gz-sensors7.yaml
gz-sensors8.yaml
gz-sim7.yaml
gz-transport13.yaml
gz-utils3.yaml
sdformat13.yaml
sdformat14.yaml

* Part of https://github.com/gazebo-tooling/release-tools/issues/578
* Follow up to
* https://github.com/gazebo-tooling/gazebodistro/pull/116
* https://github.com/gazebo-tooling/gazebodistro/pull/115
1. Update all Garden versions to use brand-new `gz` branches - except for `gz-sim`, which is still being forward-ported from Fortress
2. Create new `.yaml` files for the new post-garden major versions. They have the same dependencies as their N-1 versions, but use their own `main` branches

Update Garden branches, create post-Garden files

---

gz-launch7.yaml

Should fix https://github.com/gazebosim/gz-launch/pull/195
Current `main` is [gz-launch7](https://github.com/gazebosim/gz-launch/blob/main/CMakeLists.txt#L6) which [uses gz-sim7](https://github.com/gazebosim/gz-launch/blob/main/CMakeLists.txt#L91-L92).
Tested: [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign_launch-ci-win&build=74)](https://build.osrfoundation.org/job/ign_launch-ci-win/74/)

Use gz-sim7 in gz-launch7 by now

---

gz-gui8.yaml

Signed-off-by: Ian Chen <ichen@osrfoundation.org>
https://github.com/gazebo-tooling/release-tools/issues/853

Bump gui8 to depend on rendering8

---

gz-sim8.yaml

Signed-off-by: Ian Chen <ichen@osrfoundation.org>
https://github.com/gazebo-tooling/release-tools/issues/853

Bump sim8 to depend on gui8, sensors8, and rendering8 (main branch)

---

gz-launch7.yaml

Signed-off-by: Ian Chen <ichen@osrfoundation.org>
https://github.com/gazebo-tooling/release-tools/issues/853

Bump launch7 to depend on sim8, gui8, sensors8, and rendering8 (main branch)

---

gz-fuel-tools9.yaml
gz-gui8.yaml
gz-launch7.yaml
gz-sensors8.yaml
gz-sim8.yaml
gz-transport13.yaml

We probably need some other bumps:
```
gazebodistro on  jrivero/msgs10 [!] underwent 14s❯ grep -R msgs9 *
collection-garden.yaml:    version: gz-msgs9
gz-fuel-tools8.yaml:    version: gz-msgs9
gz-fuel-tools9.yaml:    version: gz-msgs9
gz-gui7.yaml:    version: gz-msgs9
gz-gui8.yaml:    version: gz-msgs9
gz-launch6.yaml:    version: gz-msgs9
gz-launch7.yaml:    version: gz-msgs9
gz-msgs9.yaml:    version: gz-msgs9
gz-sensors7.yaml:    version: gz-msgs9
gz-sensors8.yaml:    version: gz-msgs9
gz-sim7.yaml:    version: gz-msgs9
gz-sim8.yaml:    version: gz-msgs9
gz-transport12.yaml:    version: gz-msgs9
```
The ones duplicated in the list I assume.

Bumps for msgs10

---

collection-harmonic.yaml
gz-gui8.yaml
gz-launch7.yaml
gz-physics7.yaml
gz-sim8.yaml

In addition, I also updated the files to use gz-rendering8 and sdf14 stable branches that were missed in previous PRs

Use gz-physics7 and gz-gui8 stable branches in harmonic

---

collection-harmonic.yaml
gz-launch7.yaml
gz-physics7.yaml
gz-sensors8.yaml
gz-sim8.yaml

Merge when we are ready for pre-release
Found and update more instances in harmonic yaml files that still use `main`

Use gz-sim8 and gz-launch7 stable branches in harmonic

---

collection-ionic.yaml

No version bumps yet, just a placeholder collection file until bumps happen.

Add Ionic collection

---

gz-fuel-tools10.yaml
gz-gui9.yaml
gz-launch8.yaml
gz-msgs11.yaml
gz-physics8.yaml
gz-rendering9.yaml
gz-sensors9.yaml
gz-sim9.yaml
gz-transport14.yaml
sdformat15.yaml

Use `main` branches for libraries that haven't been bumped yet (libraries that were bumped for Harmonic). Other than changing the branch to `main`, this doesn't update any dependencies. That will be done in follow up PRs.

Update Ionic deps

---

gz-utils3.yaml

gz-utils3: use gz-cmake4 in ionic

---

gz-plugin2.yaml
gz-plugin3.yaml

gz-plugin depends on gz-tools (see https://github.com/gazebosim/gz-plugin/blob/c45ddf2033cd5191aff9239b9710dd07c5e9b24e/.github/ci/packages.apt#L2), but they were missing from gazebodistro.

Add gz-tools to gz-plugin

---

update_dependency_version.py

Script to update version/branch of library in all downstream libraries

---

collection-ionic.yaml
gz-launch8.yaml
gz-physics8.yaml
gz-sim9.yaml

Ionic: use stable branch for gz-physics8

---

collection-ionic.yaml
gz-common6.yaml
gz-fuel-tools10.yaml
gz-gui9.yaml
gz-launch8.yaml
gz-physics8.yaml
gz-rendering9.yaml
gz-sensors9.yaml
gz-sim9.yaml

Ionic: use stable branch for gz-common6

---

collection-ionic.yaml
gz-launch8.yaml

Ionic: use stable branch for gz-launch8

---

collection-ionic.yaml
gz-launch8.yaml
gz-sim9.yaml

Draft - requires the gz-sim9 branch to be created first

Ionic: use stable branch for gz-sim9

---

gz-gui10.yaml

gz-gui10: Bump gz-transport and others in jetty

---

gz-sensors10.yaml

gz-sensors10: Bump gz-transport and others in jetty

---

gz-gui10.yaml
gz-sensors10.yaml
gz-sim10.yaml

gz-sim10: Bump gz-transport and others in jetty

---

gz-gui10.yaml
gz-launch9.yaml
gz-sensors10.yaml
gz-sim10.yaml

gz-launch9: Bump gz-transport and others in jetty

---

collection-jetty.yaml

gz-jetty: Bump gz-transport and others in jetty

---

.github/workflows/lint.yaml

The 20.04 runners have already been disabled, so upgrade to 24.04 and a newer python version.

Use 24.04, python 3.12 in lint.yaml workflow

---

gz-math9.yaml

gz-math9: Bump gz-cmake and others in jetty

---

gz-utils4.yaml

gz-utils4: Bump gz-cmake and others in jetty

---

sdformat16.yaml

sdformat16: Bump gz-cmake and others in jetty

---

gz-plugin4.yaml

gz-plugin4: Bump gz-cmake and others in jetty

---

gz-common7.yaml

gz-common7: Bump gz-cmake and others in jetty

---

gz-msgs12.yaml

gz-msgs12: Bump gz-cmake and others in jetty

---

gz-physics9.yaml

gz-physics9: Bump gz-cmake and others in jetty

---

gz-rendering10.yaml

gz-rendering10: Bump gz-cmake and others in jetty

---

gz-transport15.yaml

gz-transport15: Bump gz-cmake and others in jetty

---

gz-gui10.yaml

gz-gui10: Bump gz-cmake and others in jetty

---

gz-sim10.yaml

gz-sim10: Bump gz-cmake and others in jetty

---

gz-launch9.yaml

gz-launch9: Bump gz-cmake and others in jetty

---

collection-jetty.yaml

gz-jetty: Bump gz-cmake and others in jetty

---

gz-tools3.yaml

Needed by https://github.com/gazebosim/gz-tools/pull/157.

gz-tools3: use gz-cmake main branch

---

collection-jetty.yaml
gz-cmake5.yaml
gz-common7.yaml
gz-fuel-tools11.yaml
gz-gui10.yaml
gz-launch9.yaml
gz-math9.yaml
gz-msgs12.yaml
gz-physics9.yaml
gz-plugin4.yaml
gz-rendering10.yaml
gz-sensors10.yaml
gz-sim10.yaml
gz-tools3.yaml
gz-transport15.yaml
gz-utils4.yaml
sdformat16.yaml

Part of https://github.com/gazebosim/gz-jetty/issues/19

gz-jetty: Use stable branch for gz-cmake5

---

collection-jetty.yaml
gz-common7.yaml
gz-fuel-tools11.yaml
gz-gui10.yaml
gz-launch9.yaml
gz-math9.yaml
gz-msgs12.yaml
gz-physics9.yaml
gz-plugin4.yaml
gz-rendering10.yaml
gz-sensors10.yaml
gz-sim10.yaml
gz-transport15.yaml
gz-utils4.yaml
sdformat16.yaml

Part of https://github.com/gazebosim/gz-jetty/issues/21

gz-jetty: Use stable branch for gz-utils4

---

collection-jetty.yaml
gz-common7.yaml
gz-fuel-tools11.yaml
gz-gui10.yaml
gz-launch9.yaml
gz-physics9.yaml
gz-rendering10.yaml
gz-sensors10.yaml
gz-sim10.yaml

Part of https://github.com/gazebo-tooling/release-tools/pull/1370

gz-jetty: Use stable branch for gz-common7

---

collection-jetty.yaml
gz-common7.yaml
gz-fuel-tools11.yaml
gz-gui10.yaml
gz-launch9.yaml
gz-math9.yaml
gz-msgs12.yaml
gz-physics9.yaml
gz-rendering10.yaml
gz-sensors10.yaml
gz-sim10.yaml
gz-transport15.yaml
sdformat16.yaml

Part of https://github.com/gazebosim/gz-jetty/issues/22.

Use stable branch gz-math9 in jetty packages

---

collection-jetty.yaml
gz-launch9.yaml
gz-physics9.yaml
gz-sim10.yaml

Part of https://github.com/gazebosim/gz-jetty/issues/29.

Jetty: use stable branch gz-physics9

---

collection-jetty.yaml
gz-gui10.yaml
gz-launch9.yaml
gz-sim10.yaml

Part of https://github.com/gazebosim/gz-jetty/issues/32

gz-jetty: Use stable branch for gz-gui10

---

collection-jetty.yaml
gz-launch9.yaml
gz-sim10.yaml

Part of https://github.com/gazebosim/gz-jetty/issues/33

gz-jetty: Use stable branch for gz-sim10
